parameter_defaults:
  OvercloudControllerFlavor: "controller"
  OvercloudComputeFlavor: "compute"
  OvercloudComputeOvsDpdkFlavor: "computeovsdpdk"
  OvercloudComputeOvsDpdkSriovFlavor: "computeovsdpdk"

  ControllerCount: 1
  ComputeOvsDpdkSriovCount: 2

  NtpServer: "clock.redhat.com"
  #TimeZone: Kolkata
  SshServerOptions:
    UseDns: 'no'
    #TenantInterfaceRoutes:
    #  - test1: 1
    #    test2: 2
