resource_registry:
  OS::TripleO::ComputeOvsDpdkSriov::Net::SoftwareConfig: nic-configs/computeovsdpdk.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: nic-configs/controller.yaml

parameter_defaults:
  DnsServers: ['10.11.5.19']

  ControlPlaneDefaultRoute: "192.168.50.1"
  ControlPlaneSubnetCidr: "24"

  ControlPlaneSubnet: leaf0
  ControllerControlPlaneSubnet: leaf0
  ComputeControlPlaneSubnet: leaf0
  ComputeOvsDpdkSriovControlPlaneSubnet: leaf0

  NeutronExternalNetworkBridge: "br-ex"
  NeutronTunnelTypes: 'vxlan'
  NeutronNetworkType: ['vxlan', 'vlan']
  NeutronBridgeMappings: 'datacentre:br-ex,data1:br-link0,data2:br-link1'
  NeutronNetworkVLANRanges: 'data1:502:505,data2:506:510'

  NovaPCIPassthrough:
    - vendor_id: "8086"
      product_id: "6f02"
