resource_registry:
  OS::TripleO::ComputeOvsDpdkSriov::PreNetworkConfig: /usr/share/openstack-tripleo-heat-templates/extraconfig/pre_network/host_config_and_reboot.yaml

parameter_defaults:

 ComputeOvsDpdkParameters:
  OvsEnableDpdk: true
  OvsDpdkCoreList: 0-1,12-13
  OvsDpdkMemoryChannels: 4
  OvsPmdCoreList: 10-11,22-23
  NovaVcpuPinSet: 4-9,16-21
  IsolCpusList: 4-11,16-23
  KernelArgs: default_hugepagesz=1GB hugepagesz=1G hugepages=32 intel_iommu=on iommu=pt isolcpus=4-11,16-23
  #TunedProfileName: ""
