resource_registry:
  OS::TripleO::ComputeOvsDpdk::Net::SoftwareConfig: nic-configs/computeovsdpdk.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: nic-configs/controller.yaml

parameter_defaults:
  ControlPlaneDefaultRoute: "192.168.24.1"
  ControlPlaneSubnetCidr: "24"
  DnsServers: ['10.11.5.19']
  EC2MetadataIp: "192.168.24.1"

  ExternalAllocationPools: [{'start': '10.9.88.200', 'end': '10.9.88.211'}]
  ExternalNetCidr: "10.9.88.0/24"
  #ExternalNetworkVlanID: 135
  NeutronExternalNetworkBridge: "''"
  ExternalInterfaceDefaultRoute: "10.9.88.254"

  InternalApiNetCidr: 10.120.81.0/24
  StorageNetCidr: 10.120.82.0/24
  StorageMgmtNetCidr: 10.120.83.0/24
  TenantNetCidr: 10.120.84.0/24
  InternalApiNetworkVlanID: 131 
  StorageNetworkVlanID: 132 
  StorageMgmtNetworkVlanID: 133 
  TenantNetworkVlanID: 134 
  InternalApiAllocationPools: [{'start': '10.120.81.20', 'end': '10.120.81.200'}]
  StorageAllocationPools: [{'start': '10.120.82.20', 'end': '10.120.82.200'}]
  StorageMgmtAllocationPools: [{'start': '10.120.83.20', 'end': '10.120.83.200'}]
  TenantAllocationPools: [{'start': '10.120.84.20', 'end': '10.120.84.200'}]

  ControllerCount: 1
  OvercloudControllerFlavor: controller
  ComputeOvsDpdkCount: 1
  OvercloudComputeOvsDpdkFlavor: computeovsdpdk
  ComputeCount: 1
  OvercloudComputeFlavor: compute

  NeutronBridgeMappings: "datacentre:br-ex,dpdknet:br-link"
  NeutronFlatNetworks: "datacentre"
  NeutronNetworkVLANRanges: "dpdknet:210:213"
  NeutronNetworkType: ['vlan']
  NeutronTunnelTypes: ""
