# The os-net-config-mapping is used for downstream testing.
resource_registry:
  OS::TripleO::ComputeSriovMellanox::NodeUserData: /usr/share/openstack-tripleo-heat-templates/firstboot/os-net-config-mappings.yaml

parameter_defaults:
  NetConfigDataLookup:
    node1:
      dmiString: "system-uuid"
      id: "4c4c4544-0042-5310-8056-c8c04f4e5232"
      nic1: em1
      nic2: em2
      nic3: p4p1
      nic4: p4p2
      nic5: p4p3
      nic6: p4p4
      nic7: p5p1
      nic8: p5p2
      nic9: p7p1
      nic10: p7p2
      nic11: p7p3
      nic12: p7p4
