parameter_defaults:
  ControllerCount: 1
  ComputeOvsDpdkCount: 1
  ComputeSriovCount: 1
  OvercloudControllerFlavor: control
  OvercloudComputeOvsDpdkFlavor: compute
  OvercloudComputeSriovFlavor: compute

  #TODO: br-ex needs to be re-looked as nfv ref nic configs does not have br-ex bridge

  # NeutronBridgeMappings translates to neutron::agents::ml2::ovs::bridge_mappings
  NeutronBridgeMappings: "dpdknet:br-link"
  # NeutronFlatNetworks translates to neutron::plugins::ml2::flat_networks
  NeutronFlatNetworks: "datacentre"
  # NeutronNetworkType translates to neutron::plugins::ml2::tenant_network_types
  NeutronNetworkType: ['vlan']
  # NeutronTunnelTypes translates to neutron::agents::ml2::ovs::tunnel_types
  NeutronTunnelTypes: ""

  #TimeZone: Kolkata
