resource_registry:
  OS::TripleO::ComputeOvsDpdk::Net::SoftwareConfig: ../nic-configs-dsal/computeovsdpdk.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: ../nic-configs-dsal/controller.yaml

parameter_defaults:
  ControlPlaneDefaultRoute: "172.16.0.1"
  ControlPlaneSubnetCidr: "24"
  DnsServers: ['10.11.5.19']
  EC2MetadataIp: "172.16.0.1"

  ExternalAllocationPools: [{'start': '10.60.19.200', 'end': '10.60.19.251'}]
  ExternalNetCidr: "10.60.19.0/24"
  #ExternalNetworkVlanID: 10
  NeutronExternalNetworkBridge: "''"
  ExternalInterfaceDefaultRoute: "10.60.19.1"

  InternalApiNetCidr: 10.150.81.0/24
  StorageNetCidr: 10.150.82.0/24
  StorageMgmtNetCidr: 10.150.83.0/24
  TenantNetCidr: 10.150.84.0/24
  InternalApiNetworkVlanID: 81
  StorageNetworkVlanID: 82
  StorageMgmtNetworkVlanID: 83
  TenantNetworkVlanID: 84
  InternalApiAllocationPools: [{'start': '10.150.81.20', 'end': '10.150.81.200'}]
  StorageAllocationPools: [{'start': '10.150.82.20', 'end': '10.150.82.200'}]
  StorageMgmtAllocationPools: [{'start': '10.150.83.20', 'end': '10.150.83.200'}]
  TenantAllocationPools: [{'start': '10.150.84.20', 'end': '10.150.84.200'}]

  # NeutronNetworkVLANRanges translates to neutron::plugins::ml2::network_vlan_ranges
  NeutronNetworkVLANRanges: "dpdknet:210:214"

  LocalProvisioningNicName: nic1
  LocalUnusedNicName: nic2
