resource_registry:
  OS::TripleO::ComputeOvsDpdk::Net::SoftwareConfig: nic-configs/computeovsdpdk.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: nic-configs/controller.yaml
  OS::TripleO::ComputeOvsDpdk::Ports::ExternalPort: /usr/share/openstack-tripleo-heat-templates/network/ports/noop.yaml
  OS::TripleO::ComputeOvsDpdk::Ports::InternalApiPort: /usr/share/openstack-tripleo-heat-templates/network/ports/internal_api.yaml
  OS::TripleO::ComputeOvsDpdk::Ports::ManagementPort: /usr/share/openstack-tripleo-heat-templates/network/ports/noop.yaml
  OS::TripleO::ComputeOvsDpdk::Ports::StorageMgmtPort: /usr/share/openstack-tripleo-heat-templates/network/ports/noop.yaml
  OS::TripleO::ComputeOvsDpdk::Ports::StoragePort: /usr/share/openstack-tripleo-heat-templates/network/ports/storage.yaml
  OS::TripleO::ComputeOvsDpdk::Ports::TenantPort: /usr/share/openstack-tripleo-heat-templates/network/ports/tenant.yaml

parameter_defaults:
  ControlPlaneDefaultRoute: "192.168.24.1"
  ControlPlaneSubnetCidr: "24"
  DnsServers: ['10.11.5.19']
  EC2MetadataIp: "192.168.24.1"

  ExternalAllocationPools: [{'start': '172.30.0.200', 'end': '172.30.0.211'}]
  ExternalNetCidr: "172.30.0.0/24"
  #ExternalNetworkVlanID: 135
  NeutronExternalNetworkBridge: "'br-ex'"
  ExternalInterfaceDefaultRoute: "172.30.0.1"

  InternalApiNetCidr: 10.120.81.0/24
  StorageNetCidr: 10.120.82.0/24
  StorageMgmtNetCidr: 10.120.83.0/24
  TenantNetCidr: 10.120.84.0/24
  InternalApiNetworkVlanID: 221
  StorageNetworkVlanID: 222
  StorageMgmtNetworkVlanID: 223
  TenantNetworkVlanID: 224
  InternalApiAllocationPools: [{'start': '10.120.81.20', 'end': '10.120.81.200'}]
  StorageAllocationPools: [{'start': '10.120.82.20', 'end': '10.120.82.200'}]
  StorageMgmtAllocationPools: [{'start': '10.120.83.20', 'end': '10.120.83.200'}]
  TenantAllocationPools: [{'start': '10.120.84.20', 'end': '10.120.84.200'}]

  ControllerCount: 3
  ComputeOvsDpdkCount: 1
  OvercloudControlFlavor: controller
  OvercloudComputeOvsDpdkFlavor: computeovsdpdk

  NeutronExternalNetworkBridge: "br-ex"
  NeutronTunnelTypes: 'vxlan'
  NeutronNetworkType: ['vxlan', 'vlan']
  NeutronBridgeMappings: 'datacentre:br-ex,tenant:br-tenant'
  NeutronNetworkVLANRanges: "tenant:225:226"

  ComputeOvsDpdkParameters:
    IsolCpusList: 2-23,26-47
    KernelArgs: default_hugepagesz=1GB hugepagesz=1G hugepages=126 intel_iommu=on iommu=pt isolcpus=2-23,26-47
    OvsDpdkCoreList: 0,1,24,25
    OvsDpdkSocketMemory: 2048,1024
    OvsPmdCoreList: 7,16,31,40
    NovaVcpuPinSet: 2-6,8-15,17-23,26-30,32-39,41-47

  NtpServer: "clock.redhat.com"
