parameter_defaults:
  OvercloudControllerFlavor: "controller"
  OvercloudComputeFlavor: "compute"
  OvercloudComputeOvsDpdkFlavor: "computeovsdpdk"

  NtpServer: "clock.redhat.com"
  #TimeZone: Kolkata
  SshServerOptions:
    UseDns: 'no'

  # neutron/auth_url in nova.conf is set to ctlplane, override to internal_api
  ServiceNetMap:
    KeystoneAdminApiNetwork: internal_api
