parameter_defaults:
  OvercloudComputeOvsDpdkFlavor: compute
  
  NeutronBridgeMappings: "dpdknet:br-link"
  NeutronFlatNetworks: "datacentre"
  NeutronNetworkType: ['vlan']
  NeutronTunnelTypes: ""

  #TimeZone: Kolkata
  SshServerOptions:
    UseDns: 'no'
