parameter_defaults:
  OvercloudControllerFlavor: "controller"
  OvercloudComputeOvsDpdkFlavor: "compute"

  NeutronBridgeMappings: "dpdknet:br-link"
  NeutronFlatNetworks: "datacentre"
  NeutronNetworkType: ['vlan']
  NeutronTunnelTypes: ""

  NtpServer: "clock.redhat.com"
  #TimeZone: Kolkata
  SshServerOptions:
    UseDns: 'no'
