resource_registry:
  OS::TripleO::ComputeOvsDpdk::Net::SoftwareConfig: nic-configs/computeovsdpdk.yaml
  OS::TripleO::Compute::Net::SoftwareConfig: nic-configs/compute.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: nic-configs/controller.yaml

parameter_defaults:
  DnsServers: ['10.11.5.19']
  NeutronExternalNetworkBridge: "''"

  NeutronNetworkVLANRanges: "dpdknet:107:111"
  NeutronBridgeMappings: "dpdknet:br-link"
  NeutronFlatNetworks: "datacentre"
  NeutronNetworkType: ['vxlan']
  NeutronTunnelTypes: "vxlan"
