resource_registry:
  OS::TripleO::ComputeOvsDpdk::Net::SoftwareConfig: nic-configs/computeovsdpdk.yaml
  OS::TripleO::Controller::Net::SoftwareConfig: nic-configs/controller.yaml
  OS::TripleO::NodeExtraConfigPost: post-install.yaml

parameter_defaults:
  ControlPlaneDefaultRoute: "172.120.0.1"
  ControlPlaneSubnetCidr: "24"
  DnsServers: ['10.11.5.19']
  EC2MetadataIp: "172.120.0.1"

  ExternalAllocationPools: [{'start': '10.9.88.200', 'end': '10.9.88.211'}]
  ExternalNetCidr: "10.9.88.0/24"
  #ExternalNetworkVlanID: 135
  NeutronExternalNetworkBridge: "''"
  ExternalInterfaceDefaultRoute: "10.9.88.254"

  InternalApiNetCidr: 10.120.81.0/24
  StorageNetCidr: 10.120.82.0/24
  StorageMgmtNetCidr: 10.120.83.0/24
  TenantNetCidr: 10.120.84.0/24
  InternalApiNetworkVlanID: 131
  StorageNetworkVlanID: 132
  StorageMgmtNetworkVlanID: 133
  TenantNetworkVlanID: 134
  InternalApiAllocationPools: [{'start': '10.120.81.20', 'end': '10.120.81.200'}]
  StorageAllocationPools: [{'start': '10.120.82.20', 'end': '10.120.82.200'}]
  StorageMgmtAllocationPools: [{'start': '10.120.83.20', 'end': '10.120.83.200'}]
  TenantAllocationPools: [{'start': '10.120.84.20', 'end': '10.120.84.200'}]

  ControllerCount: 1
  ComputeOvsDpdkCount: 1
  OvercloudControlFlavor: control
  OvercloudComputeOvsDpdkFlavor: compute

  NeutronBridgeMappings: "datacentre:br-ex,dpdknet:br-link"
  NeutronFlatNetworks: "datacentre"
  NeutronNetworkVLANRanges: "dpdknet:210:214"
  NeutronNetworkType: ['vlan']
  NeutronTunnelTypes: ""

  NeutronDpdkMemoryChannels: "4"

  NeutronDatapathType: "netdev"
  NeutronDpdkDriverType: "vfio-pci"
  NovaReservedHostMemory: 4096
  NovaSchedulerDefaultFilters: "RamFilter,ComputeFilter,AvailabilityZoneFilter,ComputeCapabilitiesFilter,ImagePropertiesFilter,PciPassthroughFilter,NUMATopologyFilter"

  ComputeOvsDpdkParameters:
    KernelArgs: "intel_iommu=on iommu=on default_hugepagesz=1GB hugepagesz=1G hugepages=64 isolcpus=10-87"
    IsolCpusList: "10-87"
    OvsPmdCoreList: "10,11,22,23"
    OvsDpdkCoreList: "0,1,2,3,4,5,6,7,8,9"
    OvsDpdkSocketMemory: "1024,1024"

  NovaVcpuPinSet: "12-21,24-87"
  NeutronVhostuserSocketDir: '/var/lib/vhost_sockets'

  # Not used, but required
  NeutronDpdkCoreList: "'0'"
  NeutronDpdkMemoryChannels: "4"
