---
- hosts: localhost
  gather_facts: no
  vars:
    rhel_image_path: "/home/stack/rhel-server-7.5-x86_64-kvm.qcow2"
    public_key_file: "/home/stack/.ssh/id_rsa.pub"
  tasks:
    - name: "Get the existing flavors list"
      os_flavor_facts:
      register: flavors_list

    - set_fact:
        flavor_name_list: "{{ flavor_name_list | default([]) + [item['name']] }}"
      with_items: "{{ flavors_list.ansible_facts.openstack_flavors }}"

    - name: "Ensure the environment is using overcloudrc"
      fail:
        msg: "Source overcloudrc file instead of stackrc file"
      when:
        - flavor_name_list is defined
        - "'baremetal' in flavor_name_list"

    - name: "Create RHEL image"
      os_image:
        name: rhel
        filename: "{{ rhel_image_path }}"

    - name: "Create a keypair"
      os_keypair:
        state: present
        name: stack_user_key
        public_key_file: "{{ public_key_file }}"

    - name: "Create flavor with hugepages"
      os_nova_flavor:
        name: "m1.nano"
        vcpus: 4
        ram: 4096
        disk: 40
        extra_specs:
          "hw:mem_page_size": large
          "hw:emulator_threads_policy": isolate
          "hw:cpu_policy": dedicated

    - name: "Create Neutron Public Network"
      os_network:
        name: public
        provider_network_type: flat
        provider_physical_network: datacentre
        external: yes

    - name: "Create Subnet for Neutron Public Network"
      os_subnet:
        name: public
        network_name: public
        cidr: 192.168.10.200/29
        dns_nameservers:
          - 8.8.8.8

    - name: "Create Tenant Network"
      os_network:
        name: tenant1

    - name: "Create Subnet for Tenant Network"
      os_subnet:
        name: tenant1
        network_name: tenant1
        cidr: 192.1.1.0/24

    - name: "Create Router for Tenant Network"
      os_router:
        name: tenant1_router
        network: public
        interfaces:
          - net: tenant1
            subnet: tenant1

    - name: "Create a guest VM"
      os_server:
        name: tenant1
        flavor: m1.nano
        network: tenant1
        image: rhel
        key_name: stack_user_key
